#!/bin/sh

dir=~/.dotfiles
olddir=~/.dotfiles/.dotfiles.old
files=(".bash_profile"
       ".bashrc"
       ".gitconfig"
       ".inputrc"
       ".vimrc"
       ".Xresources")

mkdir -p $olddir

for file in ${files[*]}; do
    if [ -f ~/$file ]; then
        mv ~/$file $olddir
    fi
    ln -s $dir/$file ~/$file
done
