#!/bin/bash

dir=~/.dotfiles
olddir=~/.dotfiles/.dotfiles.old
files=".bashrc .inputrc .vimrc .Xresources"

mkdir -p $olddir

for file in $files; do
    mv ~/$file $olddir
    ln -s $dir/$file ~/$file
done
